name: compilazione relazione

run-name: Relazione pdf

on:
  push:
    paths:
      - "relazione/**"
jobs:
  compilazione:
    runs-on: ubuntu-latest

    steps:
      - name: passo1 installazione typst
        uses: Homebrew/actions/setup-homebrew@master
      - name: passo2 installazione typst
        run: |
          brew install typst
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Compilazione
        run: |
          typst compile DocsSrc/main.typ relazione.pdf --font-path=assets/fonts
      - name: Configure Git
        run: |
          git config --global user.email "azione@azione.com"
          git config --global user.name "GitHub Actions"
      - name: Add and commit
        run: |
          git add relazione.pdf
          git commit -m "Relazione compilata"
          git push
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
